// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MethodCopier
{
    internal sealed partial class Vsix
    {
        public const string Id = "MethodCopier.d3965a1f-aaaf-45cb-afa6-42404f7d854a";
        public const string Name = "MethodCopier";
        public const string Description = @"Copy a method with all dependencies";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Fidel Ernesto Diaz Andino";
        public const string Tags = "";
        public const bool IsPreview = false;
    }
}
